drop database ventas;
-- Crear base de datos Ventas
CREATE DATABASE IF NOT EXISTS Ventas
DEFAULT CHARACTER SET UTF8;

-- Poner en uso
USE Ventas;

-- Crear tabla Customer
CREATE TABLE CUSTOMER (
    CUSTNO char(8),
    CUSTFIRSTNAME varchar(50)  NOT NULL,
    CUSTLASTNAME varchar(60)  NOT NULL,
    CUSTCITY varchar(25),
    CUSTSTATE char(2),
    CUSTZIP char(10),
    CUSTBAL char(5),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTNO)
);

-- Crear tabla Employee
CREATE TABLE EMPLOYEE (
    EMPNO char(8),
    EMPFIRSTNAME varchar(50)  NOT NULL,
    EMPLASTNAME varchar(60)  NOT NULL,
    EMPPHONE char(13),
    EMPEMAIL varchar(30)  NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPNO)
);

-- Crear tabla OrderTbl
CREATE TABLE ORDERTBL (
    PEDNO char(8),
    CUSTNO char(8),
    PEDDATE DATE NOT null,
    EMPNO char(8),
    CONSTRAINT ORDERTBL_PK PRIMARY KEY (PEDNO)
);

-- Relacionar la tabla CUSTOMER - ORDERTBL
ALTER TABLE ORDERTBL 
ADD CONSTRAINT CUSTOMER_ORDERTBL
FOREIGN KEY (CUSTNO) REFERENCES CUSTOMER (CUSTNO)
;

-- Relacionar la tabla EMPLOYEE - ORDERTBL
ALTER TABLE ORDERTBL 
ADD CONSTRAINT EMPLOYEE_ORDERTBL
FOREIGN KEY (EMPNO) REFERENCES EMPLOYEE (EMPNO)
;